Company-People/Piece-Plan

public/components/plan/index.html

feat: add plan static markup

---

public/components/calender/index.html

캘린더 정적 마크업 완료

---

public/main.css

CSS 초기 설정 파일 내용 추가

---

public/components/plan/index.html
public/components/plan/style.css

feat: add plan css style

---

public/components/calender/index.html
public/components/calender/style.css
public/components/plan/index.html

네비게이션 태그 추가 및 캘린더 CSS 완료
#3 플랜 스타일 완료

캘린더 CSS 완료

---

public/components/inputmodal/index.html
public/components/inputmodal/style.css

feat:  create inputmodal

---

public/components/inputmodal/style.css

feat: modify checkbox button

---

public/components/plan/index.html
public/components/plan/style.css

feat: add plans style

---

public/core/Component.js
public/index.js
public/libs/diff.js
public/libs/eventHolder.js
public/libs/render.js

feat: add component based files

---

public/components/inputmodal/Component.js
public/components/inputmodal/PieceAdd.js
public/components/inputmodal/index.html
public/components/inputmodal/index.js
public/components/inputmodal/schema.js
public/components/inputmodal/style.css
public/components/login/Component.js
public/components/login/Login.js
public/components/login/index.html
public/components/login/index.js
public/components/login/schema.js
public/components/login/style.css
public/components/signup/Component.js
public/components/signup/Signup.js
public/components/signup/index.html
public/components/signup/index.js
public/components/signup/schema.js
public/components/signup/style.css

로그인, 회원 등록, 피스 추가 자바스크립트 기능 구현 완료

feat: create login, signup, piece add script

---

models/pieces.js
models/plans.js
public/components/index.js
public/components/plan/Plan.js
public/components/plan/PlanDaily.js
public/core/Component.js
public/index.html
public/index.js
public/libs/render.js
server.js

feat: add route code

---

public/components/detail-modal/Modal.js
public/components/detail-modal/index.html
public/components/detail-modal/index.js
public/components/detail-modal/js/Daily.js
public/components/index.js

* 병합을 위해 모달 컴포넌트 관련 로직을 수정했습니다.
* `public/components/detail-modal`

모달 컴포넌트 관련 로직 수정

---

public/components/calender/Calendar.js
public/components/nav/Nav.js

네비게이션 인수 전달

---

public/components/plan/Plan.js
public/core/Component.js
public/libs/render.js

feat: add render logic

---

public/components/calender/Calendar.js
public/main.css

각각 일자 표시 관련 CSS 작업
Calendar 내부의 임시 Mock plans 데이터 대신 models의 plans로 부터 데이터를 가져오기
getCategoryClass 함수 수정

캘린더 CSS 및 script 작업

---

models/pieces.js
models/plans.js
public/components/plan/PieceDetail.js
public/components/plan/PieceList.js
public/components/plan/Plan.js
public/components/plan/PlanPiece.js
public/core/Component.js
public/libs/render.js
public/main.css
server.js

feat: add detail modal Component

---

public/components/index.js
public/components/inputmodal/PieceAdd.js
public/components/login/Login.js
public/components/signup/Signup.js
public/index.html
public/libs/diff.js
public/libs/render.js

로그인, 회원가입 라우터 추가
로그인, 회원가입 리팩토링

feat: add login, signup to router and refactor login, signup logic

---

public/components/inputmodal/PieceAdd.js
public/components/login/Login.js
public/components/signup/Signup.js

피스 추가 컴포넌트 수정
수정 내용 : 스키마를 import해오던 것을 value를 state로 사용하도록 변경

refactor: refactor PieceAdd component to use value state 

---

public/components/plan/PieceDetail.js
public/components/plan/Plan.js
public/libs/render.js
public/main.css
server.js

fix: fix refresh error

---

public/components/inputmodal/PieceAdd.js

refactor: modify title, subtitle length limit

---

public/main.css

상세정보 모달 스타일 수정

---

public/components/inputmodal/PieceAdd.js
public/components/plan/Plan.js
public/components/plan/PlanDaily.js
public/libs/diff.js
public/main.css

feat: create event for add mobal

---

public/components/calender/Calendar.js

filteredPlan 가져오는 경우 filter 대신 find 사용
matches closest로 변경
today 및 category class 주는 함수 변경

캘린더 script 수정

---

models/users.js
public/components/inputmodal/PieceAdd.js

feat: change user mock data

---

public/components/calender/Calendar.js
public/main.css

캘린더 날짜 padding 값 수정
monthList, dayList 선언 위치 변경

캘린더 CSS 및 script 수정

---

models/pieces.js
public/components/plan/PieceAdd.js
public/components/plan/Plan.js
server.js

feat: add piece server logic

---

models/pieces.js
models/plans.js
public/components/plan/Plan.js
server.js

피스 추가 로직 추가
서버에 요청 시 새로운 피스 추가 기능 구현

feat: add new piece logic server and clien

---

models/users.js
public/components/login/Login.js
server.js

* JWT를 사용하여 로그인 인증, 인가를 구현했습니다.
* 로그아웃 시 토큰 제거하는 로직 추가 필요
* 루트 요청 시 redirect 문제 논의 및 해결 필요

JWT를 사용한 로그인 인증 & 인가 구현 작업

---

public/components/main/Main.js
public/components/signup/Signup.js

로그인 및 회원가입 버튼 이벤트 추가

---

public/main.css

date-schedule -> love-schedule 클래스 명 변경

calendar 관련 클래스명 변경

---

public/components/main/Main.js
public/components/nav/Nav.js
public/index.html
public/libs/render.js
server.js

refactor: check auth and route page

---

public/components/index.js
public/components/notFound/NotFound.js
public/libs/render.js
public/main.css

* 404 오류 페이지 컴포넌트 및 스타일링 추가
* `public/components/notFound`
* `public/main.css`

404 페이지 컴포넌트 추가

---

public/components/login/Login.js
server.js

* 로그인 컴포넌트에 알림 기능 구현
* `public/components/login`

로그인 실패 시 알림 기능 구현

---

public/components/index.js
public/components/login/Login.js
public/components/notFound/NotFound.js
public/libs/render.js
public/main.css
server.js

* 서버와 클라이언트에 회원가입 기능 관련 로직 추가
* `public/components/login`
* `public/components/signup`
* `public/components/detail-modal`
* `public/main.css`

회원가입 기능 관련한 로직 추가

---

server.js

- 로그인 관련 이슈 수정
: users를 객체 디스트럭처링 할당하지 않아서 발생한 이슈
- res.send 메서드 사용할 때 작성한 return 삭제
- `server.js

로그인 관련 이슈 해결

---

public/components/login/Login.js
public/components/signup/Signup.js
server.js

* 로그인, 회원가입 기능에 존재하는 필요없는 코드 삭제
* `public/components/login`
* `public/components/signup`

로그인, 회원가입 기능에 존재하는 필요없는 코드 삭제

---

server.js

- 회원가입 기능 관련 users 데이터를 사용하는 함수가 누락된 부분 수정
- `server.js`

회원가입 기능 관련 오류 수정 작업

---

models/pieces.js
public/components/plan/PieceDetail.js
public/components/plan/PieceItem.js
public/components/plan/PieceList.js
public/components/plan/Plan.js
public/main.css
server.js

피스 리스트의 item에 즐겨찾기 기능 추가 및 버그 수정

feat: add pieceList item favorite func

---

public/components/signup/Signup.js

회원가입의 닉네임 유효성 검사 로직 수정

---

public/components/plan/Plan.js
public/components/signup/Signup.js

인풋과 텍스트에리어의 특수문자로 인한 xss 공격 방지 및 diff 에러 해결

fix: fix input, textarea spatial charactors error

---

public/components/calender/Calendar.js
public/components/signup/Signup.js

fix: solve signup nickname error

---

public/components/login/Login.js
public/components/signup/Signup.js

fix: resolve " and ' input error

---

public/main.css

* 상세 정보 모달의 소제목의 height 값이 정상적으로 동작하지 않는 오류 수정

상세 정보 모달의 소제목 관련 오류 수정

---

README.md

README.md 파일 업데이트
